### PR TITLE
Simplify tailing

### PR DESCRIPTION
**Pull request by aperepel**
Simpler is better :) Was there a reason to use a sleep loop with -f? Maybe to avoid 'file not yet there' message from tail?

### CODE REVIEW

**Comment by lalyos** [comment]
I think it was done, because if somebody attached to the container and pressed ctrl-c, terminated the `tail -f` process, which caused terminating the whole container.

Needs testing if its still happening.

**Comment by keyki** [comment]
I think when you start the container the /var/log/ambari-agent/ambari-agent.log doesn't exist so tail -F will fail instantly causing the container to exit.

**Comment by akanto** [comment]
The /var/log/ambari-agent/ambari-agent.log log file could be touched and in that case Andrew's commit is OK.

**Comment by aperepel** [comment]
Hey guys, there's a major difference between `tail -f` and `tail -F`, I wanted to see if I'm missing something else. If we use `-F` it will stop and **wait** until the file is available - the handle can come and go any number of times, and the tail process will diligently pick up this new instance of a file every time without exiting.

I don't insist on changing something that already works, just checking that I understand a Docker container lifecycle correctly.

**Comment by keyki** [comment]
Indeed, it seems the tail on OSX is differ from this behavior.

**Pull request closed without merging**
