### PR TITLE
Set up local repo

### PR DESCRIPTION
**Pull request by dlyle65535**
This is something I find helpful when I'm working in an area with degraded network. The notion is to keep a local copy of the HDP and HDP-UTILS repos and fire up a httpd container to serve them. For ease of use, I register it with the consul instance. I use DOCKER_OPTS to overwrite repoinfo.xml to point to my local instance.

### CODE REVIEW

**Comment by mhmxs** [comment]
Good idea and i'm glad to merge. But i see two things. There are 4 commits in the pull request, i guess something went wrong during rebasing, and the request contains changes around EXPOSE_DNS. So could you please clarify it before i accept it?

**Comment by dlyle65535** [comment]
Happy to- as I was adding the local repo changes, I noticed that I didn't add the EXPOSE_DNS variables to the amb-clean and amb-settings methods. I wouldn't normally do 2 fixes in the same pull request, but as I was in the neighborhood...

I was also puzzled why the PR has 4 commits. On my fork, it's 2- merge in master and this change. I didn't dig into it as the only changes that came over were the ones I made.

commit c9a22c18d7650c45ba84dbb6f52194f81b14dc58
Author: David Lyle <dlyle65535@gmail.com>
Date:   Thu Dec 10 13:06:53 2015 -0500

    Use httpd docker image to host local HDP repo.

commit 28bc8b5284141abc92be2bdd146826d271f62586
Merge: 6366ed9 421da6e
Author: David Lyle <dlyle65535@gmail.com>
Date:   Thu Dec 10 12:32:32 2015 -0500

    Merge remote-tracking branch 'upstream/master'

commit 421da6e82137c26a98380aefa91dd1bc4df34ec6
Author: lalyos <lalyos@yahoo.com>
Date:   Wed Dec 9 10:39:39 2015 -0500

    use latest ambari image

**Comment by mhmxs** [comment]
Hi, i was investigating a bit around the EXPOSE_DNS, and something not round because it is on master 2 times, and comes with your pr at other 2 times, but the coming changes are needed, so it's a bug why they are not on master.

About the commits. We usually only rebasing branches, and i'm afraid to merge commit to master like [this](https://github.com/dlyle65535/docker-ambari/commit/28bc8b5284141abc92be2bdd146826d271f62586). I can merge PRs which contains only the change and nothing else.

So what i can do is cherry picking your change and merge (in my name :() or could you please create a new feature branch from current master without merge, and apply local repo change only? In a separate commit  would be nice the fix around the EXPOSE_DNS [amb-clean](https://github.com/dlyle65535/docker-ambari/commit/c9a22c18d7650c45ba84dbb6f52194f81b14dc58#diff-b510b2421d46c0baf98cc50ab99839b8R42) and [amb-settings](https://github.com/dlyle65535/docker-ambari/commit/c9a22c18d7650c45ba84dbb6f52194f81b14dc58#diff-b510b2421d46c0baf98cc50ab99839b8R72) lines.

Sorry for the angularity, we could not apply different policies for external commits than internal.

Thanks

**Comment by dlyle65535** [comment]
No worries, won't take long- I'll have it to you shortly.

Thanks!

-D...

**Pull request closed without merging**
