### PR TITLE
URL was returning 404, updated to new URL

### PR DESCRIPTION
**Pull request by slmingol**

### CODE REVIEW

**Comment by matyix** [comment]
Thanks for pointing out the outdated link - we can't assume that people use/have only Mac's; there is getting started guides not for all supported platforms: [Linux](https://docs.docker.com/linux/started/), [Windows](https://docs.docker.com/windows/started/) and [Mac](https://docs.docker.com/mac/started/). Can you update the PR?

**Comment by slmingol** [comment]
Agreed. I looked and didn't see a generic URL. I'll take another quick look and see if I can find a better URL.

**Comment by slmingol** [comment]
@matyix - how's that?

**Comment by matyix** [comment]
LGTM. Thanks for the pull request.

**Pull request merged**
