### PR TITLE
Added memory/cpu limitations for HDP containers and disabled swap.

### PR DESCRIPTION
**Pull request by dlyle65535**
The notion is to divide available resources by the actual cluster size
and allocate to each container. Set VM_MEMORY to the amount of memory in GB.
Will defaut to 8.

### CODE REVIEW

**Comment by mhmxs** [comment]
The idea looks good, but it should be better if those limitations are optional. The resource requirement depends on the blueprint what you install, so hard coded default value could consume too much resources. Could you please refactor the change set in this view?
Other thing, we are happy with DEBUG=1.

**Comment by dlyle65535** [comment]
Just saw you replied, Richard. This seems a little OBE by now. I'll close this one and re-do with the changes you mentioned on a more recent version.

Thanks!

**Comment by lalyos** [comment]
Hi @dlyle65535 

You can just simple use the already existing `DOCKER_OPTS` env variable. This was introduced so you can add your own specific options.

**Comment by dlyle65535** [comment]
Considered it, but thought others may find it useful as well. If you don't
agree, I won't work on it.

**Pull request closed without merging**
